### PR TITLE
Display the last revision of bundles in bundles-containing.

### LINKED ISSUE #215: /meta/bundles-containing should only return the latest version of each bundle
https://jujucharms.com/mysql/precise/28 fails to load further information on the bundles because there are a million versions of mediawiki-scalable.  We should only return the latest version per solution.

### PR DESCRIPTION
**Pull request by frankban**
Update the bundles-containing endpoint to only return the last revision of bundles by default.
Also update the revision-info endpoint to use the new denormalized fields.
This branch fixes #215

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/576/

File: internal/v4/relations.go [hunk 1]
```diff
@@ -168,26 +172,43 @@ func (h *Handler) metaBundlesContaining(entity *mongodoc.Entity, id *charm.Refer
 	if err := h.store.DB.Entities().
 		Find(bson.D{{"bundlecharms", &searchId}}).
 		Select(bson.D{{"_id", 1}, {"bundlecharms", 1}}).
-		Sort("_id").
+		Sort("-uploadtime").
```
Comment (rogpeppe) [inline internal/v4/relations.go]: Are we assuming that later revisions are always uploaded before earlier ones?
That's not necessarily the case.

File: internal/v4/relations.go [hunk 2]
```diff
@@ -168,26 +172,43 @@ func (h *Handler) metaBundlesContaining(entity *mongodoc.Entity, id *charm.Refer
...
-					return true
-				}
+	// Further filter the entities if required, by only including latest
+	// bundle revisions and/or excluding specific charm series or revisions.
+	anySeriesOrRevisionPredicate := func(e *mongodoc.Entity) bool {
+		if anySeries == anyRevision {
+			return true
+		}
+		for _, charmId := range e.BundleCharms {
+			if charmId.Name == id.Name &&
```
Comment (mhilton) [inline internal/v4/relations.go:187]: I'm not entirely sure if it would be better or not, but you could phrase this the other way round.

```
if charmId.name != id.Name {
    continue
}
...
return true
```

File: internal/v4/relations.go [hunk 3]
```diff
@@ -216,3 +237,9 @@ func filterEntities(entities []mongodoc.Entity, predicate func(*mongodoc.Entity)
 	}
 	return results
 }
+
+func noRevision(id *charm.Reference) *charm.Reference {
```
Comment (mhilton) [inline internal/v4/relations.go]: There is a similar bit of code in the search stuff, perhaps there should be a common function somewhere.

**Comment by mhilton** [comment]
:+1: on the code. I haven't done any QA. I'm not sure about the approach will charmload always ingest bundles in order? I would have thought that we should consider the latest to be based on the revision number if possible.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/593/

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/597/

File: internal/v4/relations.go (hunk 3 above)
Comment (frankban) [inline internal/v4/relations.go]: After seeing the code in search I am not sure it's worth of.

**Comment by mhilton** [comment]
:+1: QA looks good:

```
charmstore$ http :8080/v4/~lazypower/bundle/oscondemo-osconhadoop-0/meta/bundle-metadata | jq .Services[].Charm
"cs:trusty/elasticsearch-2"
"cs:trusty/hadoop-16"
"cs:trusty/hadoop-16"
"cs:trusty/hive2-1"
"cs:trusty/mysql-1"
charmstore$ http :8080/v4/~lazypower/bundle/oscondemo-osconhadoop-7/meta/bundle-metadata | jq .Services[].Charm
"cs:trusty/elasticsearch-2"
"cs:trusty/hadoop-16"
"cs:trusty/hadoop-16"
"cs:trusty/hive2-1"
"cs:trusty/mysql-1"
charmstore$ http :8080/v4/trusty/elasticsearch-2/meta/bundles-containing
HTTP/1.1 200 OK
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Origin: *
Content-Length: 106
Content-Type: application/json
Date: Fri, 28 Nov 2014 10:14:51 GMT

[
    {
        "Id": "cs:~jorge/bundle/hadoop-es-constraints-13"
    }, 
    {
        "Id": "cs:~lazypower/bundle/oscondemo-osconhadoop-7"
    }
]
```

File: internal/v4/api.go [hunk 4]
```diff
@@ -430,24 +429,18 @@ func (h *Handler) metaRevisionInfo(id *charm.Reference, path string, flags url.V
 
 	var docs []mongodoc.Entity
 	if err := h.store.DB.Entities().Find(
-		bson.D{{"baseurl", &baseURL}}).Select(
-		bson.D{{"_id", 1}}).All(&docs); err != nil {
+		bson.D{{"baseurl", &baseURL}, {"series", id.Series}}).Select(
```
Comment (rogpeppe) [inline internal/v4/api.go:432]: nice use of Series.

File: internal/v4/relations.go (hunk 2 above)
Comment (rogpeppe) [inline internal/v4/relations.go:187]: I'm not sure that would be a win here, but y'never know.

File: internal/v4/relations.go [hunk 5]
```diff
@@ -155,6 +155,10 @@ func (h *Handler) metaBundlesContaining(entity *mongodoc.Entity, id *charm.Refer
 	if err != nil {
 		return nil, badRequestf(err, "invalid value for any-revision")
 	}
+	allResults, err := parseBool(flags.Get("all-results"))
```
Comment (rogpeppe) [inline internal/v4/relations.go:158]: Please update the API specification to document this.

File: internal/v4/relations.go [hunk 6]
```diff
@@ -168,26 +172,43 @@ func (h *Handler) metaBundlesContaining(entity *mongodoc.Entity, id *charm.Refer
 	if err := h.store.DB.Entities().
 		Find(bson.D{{"bundlecharms", &searchId}}).
 		Select(bson.D{{"_id", 1}, {"bundlecharms", 1}}).
-		Sort("_id").
+		Sort("-revision", "_id").
```
Comment (rogpeppe) [inline internal/v4/relations.go]: One thought: if you sorted by ("baseurl", "series", "-revision") then you wouldn't need the map when filtering - you could just exclude an entry if it had the same base URL and series as the previous entry.

**Comment by rogpeppe** [comment]
LGTM thanks, with a couple of suggestions above.

File: internal/v4/relations.go (hunk 5 above)
Comment (frankban) [inline internal/v4/relations.go:158]: Done.

File: internal/v4/relations.go (hunk 6 above)
Comment (frankban) [inline internal/v4/relations.go]: Done.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results: http://ci.jujugui.org:8080/job/charmstore/600/

**Comment by frankban** [comment]
Thank you both!
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-merge
